### ISSUE TITLE
Not really an issue.

### ISSUE THREAD

**Issue by aichholzer** [lukeed/dset#10]
@lukeed -Good work!
This, inevitably, reminded me of [a similar thing](https://github.com/aichholzer/salvus) I wrote 4 years ago. I believe now, looking in retrospect, that my error was to use `latin` names for the exposed methods.

Might warrant a re-write/review.

**Comment by lukeed** [comment]
Haha, thanks 😜 Certainty not the first & definitely won't be the last. Utils like this are probably duplicated a million times. Mine was just for size – turned it into a module after the 6th copy-paste between projects.

And yea, maybe lol. My Latin is surely rusty, for one. 😆
