### ISSUE TITLE
Accept numbers as path elements

### ISSUE THREAD

**Issue by Andarist** [lukeed/dset#12]
This seems like a reasonable input for me. Both ramda & lodash accept it. 
```js
var obj = {}
dset(obj, ['foo', 10, 'baz'], 'bar')
```
Mentioned libraries also handle this by creating an object instead of array (like in my previously reported issue):
```js
var obj = {}
dset(obj, ['foo', 10.2, 'baz'], 'bar')
```

**Comment by lukeed** [comment]
So, basically nothing else treats numbers as indices for array creation?

**Comment by Andarist** [comment]
Every other lib creates arrays for non-negative integers, no matter if they
are represented by numbers or strings
